# -*- coding: utf-8 -*-
"""TelecomX-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwxeGjtcVxJgZdMcmHDVZTi4I4fuFTmU
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

clientes = pd.read_csv('/content/datos_2.csv')
clientes.head()

clientes.columns

clientes.info()

"""##**Remover columnas irrelevantes**"""

clientes = clientes.drop(columns=['CustomerID'])

clientes.sample(2)

columnas_fix = [
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
    'TechSupport', 'StreamingTV', 'StreamingMovies'
]

for columna in columnas_fix:
    clientes[columna] = clientes[columna].replace({'No internet service': 'No'})

clientes.head(2)

"""##**Correlación entre variables numericas**"""

clientes_numerico = clientes.select_dtypes(include=["int64", "float64"])

clientes_numerico["Churn"] = clientes["Churn"].map({"Yes": 1, "No": 0})

corr_matrix = clientes_numerico.corr()

# Visualizar heatmap
plt.figure(figsize=(10,6))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de Correlación - Variábles Numericas")
plt.show()

clientes = clientes.drop(columns=["ChargesDaily","ChargesTotal"])

clientes.head(2)

"""##**proporción por categoria**"""

columna_categorica = clientes.select_dtypes(include=["object"]).columns
columna_categorica = columna_categorica.drop("Churn")

for col in columna_categorica:
    print(f"\nAnalisis de variable: {col}")
    display(pd.crosstab(clientes[col], clientes["Churn"], normalize="index") * 100)

from sklearn.preprocessing import LabelEncoder

# 1. Identificar qué columnas siguen siendo texto (objetos)
categorical_cols = clientes.select_dtypes(include=['object']).columns

# 2. Convertirlas todas a números
le = LabelEncoder()
for col in categorical_cols:
    clientes[col] = le.fit_transform(clientes[col])

# 3. Ahora sí, define tu X y entrena el árbol
X = clientes.drop("Churn", axis=1)
y = clientes["Churn"]

from sklearn.tree import DecisionTreeClassifier
import pandas as pd

# 1. Preparar los datos (usando la copia df_rank que ya tiene Label Encoding)
# Asegúrate de que X no contenga la variable objetivo 'Churn'

# 2. Entrenar el modelo de Árbol de Decisión
# Usamos un random_state para que los resultados sean siempre iguales
clf = DecisionTreeClassifier(random_state=42, max_depth=10)
clf.fit(X, y)

# 3. Extraer la importancia de las variables (Feature Importance)
importances = clf.feature_importances_

# 4. Crear un DataFrame con el ranking
tree_rank = pd.DataFrame({
    "Variable": X.columns,
    "Importancia": importances
})

# 5. Ordenar de mayor a menor importancia
tree_rank = tree_rank.sort_values(by="Importancia", ascending=False)

tree_rank

from sklearn.model_selection import train_test_split

# Dividimos los datos: 80% para entrenar y 20% para evaluar
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Datos totales: {len(X)}")
print(f"Entrenamiento: {len(X_train)}")
print(f"Prueba: {len(X_test)}")

"""##**Entrenamiento**"""

from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Entrenar el modelo con los datos estratificados
clf.fit(X_train, y_train)

# 2. Predecir
y_pred = clf.predict(X_test)

# 3. Crear la Matriz de Confusión
cm = confusion_matrix(y_test, y_pred)

# 4. Graficarla para que sea legible
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Churn', 'Churn'],
            yticklabels=['No Churn', 'Churn'])
plt.xlabel('Predicción del Modelo')
plt.ylabel('Realidad (Actual)')
plt.title('Matriz de Confusión')
plt.show()

# 5. Ver el reporte detallado
print(classification_report(y_test, y_pred))

"""##**Evaluación**"""

from sklearn.metrics import roc_curve, roc_auc_score, precision_recall_curve

# 1. Obtener las probabilidades (necesario para la curva ROC)
# El modelo no solo dice "Sí/No", nos da la probabilidad de que sea "Sí"
y_probs = clf.predict_proba(X_test)[:, 1]

# 2. Calcular el Score AUC
auc_value = roc_auc_score(y_test, y_probs)

# 3. Graficar la Curva ROC
fpr, tpr, thresholds = roc_curve(y_test, y_probs)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'Curva ROC (area = {auc_value:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--') # Línea de azar
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Tasa de Falsos Positivos (1 - Especificidad)')
plt.ylabel('Tasa de Verdaderos Positivos (Sensibilidad)')
plt.title('Curva ROC - Evaluación del Modelo')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

"""##**Random forest**"""

from sklearn.ensemble import RandomForestClassifier

# Creamos el modelo
# n_estimators=100 significa que usaremos 100 árboles diferentes
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

# Entrenamos con los datos de entrenamiento
rf_model.fit(X_train, y_train)



"""##**Evaluando el modelo**"""

from sklearn.metrics import confusion_matrix, classification_report, ConfusionMatrixDisplay

# Realizamos las predicciones
y_pred_rf = rf_model.predict(X_test)

# Mostramos la Matriz de Confusión de forma visual
plt.figure(figsize=(8, 6))
ConfusionMatrixDisplay.from_estimator(rf_model, X_test, y_test, cmap='Greens', display_labels=['No Churn', 'Churn'])
plt.title("Matriz de Confusión - Random Forest")
plt.show()

# Imprimimos el reporte de métricas
print("--- REPORTE DE CLASIFICACIÓN RANDOM FOREST ---")
print(classification_report(y_test, y_pred_rf))

"""# 📑 Informe Ejecutivo: Análisis de Churn y Modelado Predictivo
**Proyecto:** Retención de Clientes en Telecomunicaciones  
**Autor:** Gestión de Control / Data Analysis Team

---

## 1. Resumen del Proyecto
Este análisis busca identificar los factores críticos que influyen en la cancelación de servicios (*Churn*). Se procesó un conjunto de datos con información sociodemográfica, servicios contratados y métricas financieras para construir un sistema de alerta temprana basado en Machine Learning.

---

## 2. Factores Críticos de Cancelación
Tras realizar pruebas estadísticas de **Chi-cuadrado ($\chi^2$)** y analizar la importancia de variables en modelos de ensamble, se determinaron los siguientes hallazgos:

### 🔑 Variables de Mayor Impacto
1. **Tipo de Contrato:** Los clientes con contratos **Month-to-month** representan el segmento de mayor riesgo. La estabilidad aumenta drásticamente en contratos de 1 y 2 años.
2. **Antigüedad (Tenure):** Existe una relación inversa. Los clientes en sus primeros **6 meses** tienen una tasa de fuga significativamente superior.
3. **Método de Pago:** El uso de **Electronic Check** está fuertemente correlacionado con el abandono, a diferencia de los métodos automáticos (Credit Card/Bank Transfer).
4. **Cargos Mensuales:** Los clientes con cargos elevados sin servicios de valor agregado (como protección de dispositivo o soporte técnico) tienden a desertar más rápido.



---

## 3. Metodología y Limpieza de Datos
* **Normalización:** Se consolidaron categorías redundantes (ej. "No internet service" se unificó con "No").
* **Codificación:** Se utilizó `LabelEncoder` para transformar variables categóricas en formatos procesables por los modelos.
* **Balanceo:** Se empleó la técnica de **estratificación** en la división de datos (`stratify=y`) para asegurar que la proporción de fugas fuera constante en entrenamiento y prueba.

---

## 4. Evaluación de Modelos
Se compararon tres arquitecturas distintas para determinar la mejor capacidad predictiva:

| Modelo | Ventajas
"""

